// Check service health
GET http://localhost:63723/health

###
// Create Audit Event
POST http://localhost:63723/api/v1/audit-event
Content-Type: application/json

{
    "userId": 24,
    "tenantId": 123,
    "eventType": "WORKSPACE_SIGIN_PERMITTED",
    "action": "workspace.sign-in",
    "permitted": false
}

###
